#!/bin/bash

if [ -n "$APF_FUZZY_SEARCH" ]; then
    fzf_args=""
else
    fzf_args="--exact"
fi
if [ -n "$APF_REMOVE_DEPENDENCIES" ]; then
    aur_remove_args="--recursive"
else
    aur_remove_args=""
fi
if [ -n "$APF_FLATPAK_USER" ]; then
    flatpak_level="user"
else
    flatpak_level="system"
fi
if [ -n "$APF_NO_CONFIRMATION" ]; then
    aur_install_args="--noconfirm"
    flatpak_install_args="--assumeyes"
else
    aur_install_args=""
    flatpak_install_args=""
fi
help=$(cat << EOF
Usage: $0 [FLAGS]

FLAGS:
    -f    Enable fuzzy search. Corresponding environment variable: APF_FUZZY_SEARCH
    -h    Print this message and exit
    -r    Recursively remove dependencies of AUR packages to remove. Corresponding environment variable: APF_REMOVE_DEPENDENCIES
    -u    Install Flatpak packages user-wide instead of system-wide. Corresponding environment variable: APF_FLATPAK_USER
    -y    Don't prompt for confirmation when installing packages. You will still be prompted when removing packages. Corresponding environment variable: APF_NO_CONFIRMATION

Press Tab to select multiple packages and press Enter to confirm your selection. Already installed packages will be removed and new packages will be installed.
EOF
)
while getopts 'fhruy' option; do
    case "$option" in
    	f) fzf_args="" ;;
        h) printf "$help\n"; exit 0 ;;
        r) aur_remove_args="--recursive" ;;
        u) flatpak_level="user" ;;
        y) aur_install_args="--noconfirm"; flatpak_install_args="--assumeyes" ;;
        ?) printf "$help\n"; exit 1 ;;
    esac
done

installed_aur_packages="$(mktemp)"
aur_repos="$(mktemp)"
installed_flatpak_packages="$(mktemp)"
flatpak_remotes="$(mktemp)"

choices=$(fzf $fzf_args --multi --no-sort --preview '
	choice="{1}"
	choice="${choice:1:-1}"
    repo_or_remote="${choice%%/*}"
    package_or_id="${choice#*/}"
    case "$repo_or_remote" in
        aur) repo_or_remote_color="\x1b[34m" ;;
        core) repo_or_remote_color="\x1b[33m" ;;
        extra) repo_or_remote_color="\x1b[32m" ;;
        flathub) repo_or_remote_color="\x1b[35m" ;;
        flathub-beta) repo_or_remote_color="\x1b[31m" ;;
        multilib) repo_or_remote_color="\x1b[36m" ;;
        *) repo_or_remote_color="" ;;
    esac
    printf "\x1b[1m$repo_or_remote_color$repo_or_remote\x1b[37m\x1b[0m/\x1b[1m$package_or_id"
    if cat "'"$aur_repos"'" | grep -q "^$repo_or_remote$"; then
        if cat "'"$installed_aur_packages"'" | grep -q "^$package_or_id$"; then
            printf " \x1b[32m(Installed)\x1b[37m\x1b[0m\n    Package already installed. Select to remove.\n\n"
        else
            printf "\x1b[0m\n    Package not installed. Select to install.\n\n"
        fi
        yay -Si "$package_or_id"
    elif cat "'"$flatpak_remotes"'" | grep -q "^$repo_or_remote$"; then
        if cat "'"$installed_flatpak_packages"'" | grep -q "^$repo_or_remote/$package_or_id$"; then
            printf " \x1b[32m(Installed)\x1b[37m\x1b[0m\n    Package already installed. Select to remove.\n\n"
        else
            printf "\x1b[0m\n    Package not installed. Select to install.\n\n"
        fi
        flatpak remote-info --system "$repo_or_remote" "$package_or_id"
    else
        echo "\x1b[31mError: source of package $choice is neither a repo nor a Flatpak remote!\x1b[37m"
    fi
    printf "Currently selected packages:"
    cat "{+f}" | while read -r selected_choice; do
        selected_full_package_name="${selected_choice%% *}"
        repo_or_remote="${selected_full_package_name%%/*}"
        package_or_id="${selected_full_package_name#*/}"
        case "$repo_or_remote" in
            aur) repo_or_remote_color="\x1b[34m" ;;
            core) repo_or_remote_color="\x1b[33m" ;;
            extra) repo_or_remote_color="\x1b[32m" ;;
            flathub) repo_or_remote_color="\x1b[35m" ;;
            flathub-beta) repo_or_remote_color="\x1b[31m" ;;
            multilib) repo_or_remote_color="\x1b[36m" ;;
            *) repo_or_remote_color="" ;;
        esac
        printf "\n    \x1b[1m$repo_or_remote_color$repo_or_remote\x1b[37m\x1b[0m/\x1b[1m$package_or_id\x1b[0m (to "
        if { cat "'"$aur_repos"'" | grep -q "^$repo_or_remote$" && cat "'"$installed_aur_packages"'" | grep -q "^$package_or_id$" } || \
            { cat "'"$flatpak_remotes"'" | grep -q "^$repo_or_remote$" && cat "'"$installed_flatpak_packages"'" | grep -q "^$repo_or_remote/$package_or_id$" }; then
            printf "\x1b[1m\x1b[31mremove\x1b[37m\x1b[0m"
        else
            printf "install"
        fi
        printf ")"
        if cat "'"$aur_repos"'" | grep -q "^$repo_or_remote$" && cat "'"$installed_aur_packages"'" | grep -q "^$package_or_id$" && [[ "'"$aur_remove_args"'" == *"--recursive"* ]]; then
            printf " (also remove unused dependencies)"
        fi
    done || {
        printf "none"
    }
' --bind 'start:reload(
    yay -Qq > "'"$installed_aur_packages"'"
    unformatted_aur_packages="$(yay -Pc)"
    echo "$unformatted_aur_packages" | awk '\''{print tolower($2)}'\'' | sort -u > "'"$aur_repos"'"
    aur_packages="$(echo "$unformatted_aur_packages" | awk '\''{print tolower($2) "/" $1}'\'')"
    echo "$aur_packages" | grep -v "^aur/"
    flatpak list --columns=application,origin | awk '\''{print $2 "/" $1}'\'' > "'"$installed_flatpak_packages"'"
    flatpak remotes --columns=name > "'"$flatpak_remotes"'"
    flatpak_packages="$(flatpak remote-ls --app --columns=application,origin | awk '\''!seen[$0]++ {print $2 "/" $1}'\'')"  # This line also removes duplicate lines
    echo "$flatpak_packages"
    echo "$aur_packages" | grep "^aur/"
)')
aur_packages_to_remove=""
aur_packages_to_install=""
flatpak_packages_to_remove=""
declare -A flatpak_packages_to_install
for choice in $choices; do
    full_package_name="$(echo "${choice}" | cut -d" " -f1)"
    repo_or_remote="${full_package_name%%/*}"
    package_or_id="${full_package_name#*/}"
    if cat "$aur_repos" | grep -q "^$repo_or_remote$"; then
        if cat "$installed_aur_packages" | grep -q "^$package_or_id$"; then
            aur_packages_to_remove+="$package_or_id "
        else
            aur_packages_to_install+="$package_or_id "
        fi
    elif cat "$flatpak_remotes" | grep -q "^$repo_or_remote$"; then
        if cat "$installed_flatpak_packages" | grep -q "^$repo_or_remote/$package_or_id$"; then
            flatpak_packages_to_remove+="$package_or_id "
        else
            flatpak_packages_to_install["$repo_or_remote"]+="$package_or_id "
        fi
    else
        echo "\x1b[31mError: source of package '$full_package_name' is neither a repo nor a Flatpak remote!\x1b[37m"
    fi
done
printf "\n\x1b[1m"
if [ -n "$aur_packages_to_remove" ]; then
    printf "Official and AUR packages to \x1b[31mremove\x1b[37m"
    if [[ "'"$aur_remove_args"'" == *"--recursive"* ]]; then
        printf " (also remove unused dependencies)"
    fi
    printf ": $aur_packages_to_remove\x1b[0m\n"
    yay -R $aur_remove_args ${aur_packages_to_remove::-1}
fi
if [ -n "$aur_packages_to_install" ]; then
    printf "Official and AUR packages to install: $aur_packages_to_install\x1b[0m\n"
    yay -S $aur_install_args ${aur_packages_to_install::-1}
fi
if [ -n "$flatpak_packages_to_remove" ]; then
    printf "Flatpak packages to \x1b[31mremove\x1b[37m ($flatpak_level-wide): $flatpak_packages_to_remove\x1b[0m\n"
    flatpak uninstall --$flatpak_level ${flatpak_packages_to_remove::-1}
fi
for remote in "${!flatpak_packages_to_install[@]}"; do
    if [[ -n "${flatpak_packages_to_install["$remote"]}" ]]; then
        packages="${flatpak_packages_to_install["$remote"]::-1}"
        printf "Flatpak packages to install from remote $remote ($flatpak_level-wide): $packages\x1b[0m\n"
        flatpak install $flatpak_install_args --$flatpak_level "$remote" $packages
    fi
done

printf "\x1b[0m"